# Generated by Django 5.0.6 on 2024-06-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logGroupName', models.CharField(max_length=100)),
                ('logStreamName', models.CharField(max_length=100)),
                ('owner', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
                ('ingestionTime', models.IntegerField()),
            ],
        ),
    ]
