# Generated by Django 5.0.6 on 2024-06-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudwatch', '0002_logcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ingestionTime',
            field=models.BigIntegerField(),
        ),
    ]
